### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by georgelgore** [learn-co-curriculum/react-forms#12]
"Whenever our state\ changes, the component re-renders,..."

what does backslack do?

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue!

We have fixed that typo and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
