### ISSUE TITLE
setState typos

### ISSUE THREAD

**Issue by mobrien829** [learn-co-curriculum/react-forms#13]
In multiple code snippets in the readme, setState is typo'd as `setStaet`. Should be easy to find with a find and replace. This is only in the example snippets, and never in the ones that are meant to be copy pasted into the code along.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @mobrien829.

We have fixed the typos and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
