### ISSUE TITLE
example code does not work as described by the READme

### ISSUE THREAD

**Issue by Marie-Burns22** [learn-co-curriculum/react-forms#17]
Hi,

I was able to learn a lot from this lesson, but there were a few confusing things about the directions and code.  Here are a couple suggestions to clarify it.

The directions for using the example code seem to imply that when you enter a new value into the input field, the input field will keep that new value when viewed in the browser. However, it reverts back to the the initial state that was set.  To fix this, I used the example code from the 'React Forms' resource at the bottom of the lab and that seemed to get it working as described by the READme.  Other people may have had better luck, but I think either the directions could be updated with screenshots to show what should happen in the browser (maybe I was misunderstanding what should happen) or the code may need to be updated to display correctly.  Maybe a complete constructor function needs to be added?

The Bonus section refers to code in the ControlledInput component, but is from early in the lesson (before the lab clearly stated which code to put in the starter code files).  It would be easier to read if that code was added to code to put in the starter code files so we could see how it all fits together more clearly.

Thank you!

**Comment by maxwellbenton** [comment]
Hi @Marie-Burns22,

Thank you for providing this thorough feedback. We've updated this lesson's Readme, clarifying the section on setting input values with state and the readme in general.

We've also added additional code examples and images, and updated the provided example files. All the code examples have now been tested and confirmed to be working. A solution branch has also been added with the final result.

These changes should help clarify this lesson for future students and resolve this issue. We apologize for any frustration this lesson may have caused, but thank you for contributing and helping future students!
