### ISSUE TITLE
No "start" script in package.json

### ISSUE THREAD

**Issue by kevwang424** [learn-co-curriculum/react-forms#5]
The instructions say that we can code along with the following instructions:

> Make sure to run npm install && npm start to see the code in the browser.

However we cannot use "npm start" because in the package.json files there is no script for "start". This actually has been happening for the last few labs and code-alongs beginning with the Props section. All the package.json files do not have a script for "start".

**Comment by Lukeghenco** [comment]
@kevwang424 I believe that you are not up to date with the right code. The package.json contains a start script. You should be able to destroy your current forked repo and get the correct code.

**Comment by kevwang424** [comment]
Hey Luke,

Thanks for checking! I think I know what the problem for me is. The labs
that I was working off of is for my cohort Web-1116 and those do not have
the script. I am assuming the new classes aren't separated by their classes
and there is like a master repo with that script.

Anyways it's fine I have been working around it. Below is the URL that I go
to for your info.

https://github.com/learn-co-students/react-forms-lab-web-1116
