### ISSUE TITLE
loginForm-test.js -> spy is called twice not once.

### ISSUE THREAD

**Issue by PCGeekBrain** [learn-co-curriculum/react-forms#6]
In `loginForm-test.js` there is an issue in the following test:

```
    it('should call the `onSubmit` callback prop when the form is being submitted', () => {
      const wrapper = shallow(<LoginForm onSubmit={spy} />);
      wrapper.find('#test-username').simulate('change', { target: { value: 'johndoe' } });
      wrapper.find('#test-password').simulate('change', { target: { value: 'supersecret' } });
      wrapper.find('form').simulate('submit', { preventDefault: spy });
      expect(spy.calledOnce, 'The `onSubmit` prop is not being called exactly once').to.be.true;
    });
```

As per the spec of the test before it, `event.preventDefault` should be called whenever the form is submitted. However, in this case `spy` is passed in as both the `event.preventDefault` override and the `onSubmit` property. Causing it to be called twice and have the test fail

A workaround a student can use is to not prevent default on valid input. However that is not the intended spec as you can see from the implementation on the solution branch or the `readme.md`. replacing 
````
expect(spy.calledOnce, 'The `onSubmit` prop is not being called exactly once').to.be.true;
````
with
````
expect(spy.calledTwice, 'The `onSubmit` prop is not being called exactly once').to.be.true;
````
solves this issue.

**Comment by PCGeekBrain** [comment]
Pull request on this repo under `learn-co-students` with comments explaining the issue can be found here: https://github.com/learn-co-students/react-forms-lab-v-000/pull/74

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and tests for the learn-co-curriculum/react-forms-lab and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
